# Generated by Django 4.2.1 on 2023-09-15 14:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=1000)),
                ('kakao', models.BooleanField(default=False)),
                ('kakao_id', models.CharField(max_length=500, null=True)),
                ('naver', models.BooleanField(default=False)),
                ('naver_id', models.CharField(max_length=500, null=True)),
                ('apple', models.BooleanField(default=False)),
                ('apple_id', models.CharField(max_length=500, null=True)),
                ('google', models.BooleanField(default=False)),
                ('google_id', models.CharField(max_length=500, null=True)),
                ('gender', models.CharField(max_length=500, null=True)),
                ('join_date', models.DateField()),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('chk_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.userinfo')),
            ],
            options={
                'db_table': 'UserLocation',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=1000)),
                ('screen', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.userinfo')),
            ],
            options={
                'db_table': 'UserFeedback',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.userinfo')),
                ('travelling', models.BooleanField(default=False)),
                ('moving_status', models.CharField(max_length=500, null=True)),
                ('current_place_id', models.CharField(max_length=500, null=True)),
                ('travel_skd_id', models.ForeignKey(db_column='skd_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.scheduleinfo')),
            ],
            options={
                'db_table': 'UserStatus',
            },
        ),
    ]
