# Generated by Django 4.2.1 on 2023-09-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('schedule', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snspost',
            name='accom_id',
            field=models.ForeignKey(db_column='accom_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.accommodation'),
        ),
        migrations.AddField(
            model_name='snspost',
            name='place_id',
            field=models.ForeignKey(db_column='place_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.placeinfo'),
        ),
        migrations.AddField(
            model_name='snspost',
            name='restro_id',
            field=models.ForeignKey(db_column='restro_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.restaurant'),
        ),
        migrations.AddField(
            model_name='snspost',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userinfo'),
        ),
        migrations.AddField(
            model_name='snslikes',
            name='post_id',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='community.snspost'),
        ),
        migrations.AddField(
            model_name='snslikes',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userinfo'),
        ),
        migrations.AlterUniqueTogether(
            name='snslikes',
            unique_together={('post_id', 'user_id')},
        ),
    ]
