# Generated by Django 4.2.1 on 2023-09-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleinfo',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.userinfo'),
        ),
        migrations.AddField(
            model_name='restrostatus',
            name='restro_id',
            field=models.ForeignKey(db_column='restro_id', on_delete=django.db.models.deletion.CASCADE, to='schedule.restaurant'),
        ),
        migrations.AddField(
            model_name='placestatus',
            name='place_id',
            field=models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, to='schedule.placeinfo'),
        ),
    ]
